version: '3.1'

services:
  ubo-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ubo
    volumes:
    - ${DB_DATA}:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
  ubo-solr:
    image: vzgreposis/ubo-solr:main
    restart: always
    volumes:
    - ${SOLR_DATA}:/opt/solr-data
    environment:
      SOLR_HOME: /opt/solr-data
    ports:
      - ${SOLR_HTTP}:8983
  ubo:
    image: vzgreposis/ubo:main
    restart: always
    environment:
      APP_CONTEXT: ${APP_CONTEXT}
      JDBC_NAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASSWORD}
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://ubo-db:5432/ubo
      SOLR_URL: http://ubo-solr:8983
      SOLR_CLASSIFICATION_CORE: ubo-classification
      SOLR_CORE: ubo
    volumes:
    - ${APP_HOME}:/mcr/home/
    - ${APP_DATA}:/mcr/data/
    - ${APP_TMP}:/mcr/tmp/
    - ${APP_LOG}:/mcr/logs/
    depends_on:
      - ubo-db
      - ubo-solr
    ports:
      - ${APP_HTTP}:8080
      - ${APP_AJP}:8009
